### ISSUE TITLE
demo 브랜치 머지 및 리팩토링

### ISSUE THREAD

**Issue by ja7811** [umc-owncast/OwnCast_backend#87]
`demo` 브랜치에서 개발한 기능 `develop`으로 머지 
\+ 리팩토링
\+ 추가로 필요한 기능 개발

## TODO
- [x] 코드 리팩토링
- [x] 스크립트로 캐스트 생성 시에도 GPT로 문장 구분하도록 변경
- [x] 스크립트로 생성된 캐스트로 구분자로 파싱하도록 변경
- [x] `develop`으로 머지
